### ISSUE TITLE
Open Folders Error

### ISSUE THREAD

**Issue by carldister** [Cschimpf/Complex-It#1]
When you have the Complex-It folder open in Windows, and, the data folder open in another instance in Windows, the save function in the kmeans cluster has an issue.  You need to have just the Complex-It folder open

**Comment by Cschimpf** [comment]
Yeah I've seen this, I think it is a Shiny problem, not sure there is away around it, but good to note here. Haven't looked hard into it either though

**Comment by Cschimpf** [comment]
K-means save function has been pushed to report tab and no longer part of k-means tab. This error is fixed.
