### ISSUE TITLE
Clicking Save Twice

### ISSUE THREAD

**Issue by carldister** [Cschimpf/Complex-It#2]
After running a Kmeans Clustering, then going to save the data, I have to hit the save button twice.  My guess is the first time is for the data with appended cluster number, and the second time is for the cluster stats

**Comment by Cschimpf** [comment]
Haven't had this happen, I will check out.

**Comment by Cschimpf** [comment]
Per our discussion on gmail I am closing for now, unless this problem re-emerges.
