### ISSUE TITLE
Kmeans Prediction File Same Size Only

### ISSUE THREAD

**Issue by carldister** [Cschimpf/Complex-It#4]
If prediction is checked, and a new file is uploaded then saved, this only works well if the new file has the same number of cases (rows) as the original training set of cases (rows)

**Comment by Cschimpf** [comment]
I think I'd have to see the code. Is it still using the same uploaded data file as before?

**Comment by carldister** [comment]
Hi Corey - Working on this one! - Carl

**Comment by Cschimpf** [comment]
Gotcha, you are noting these for yourself too, sorry, haha. That's a smart thing to do.

**Comment by Cschimpf** [comment]
Fixed.
