### ISSUE TITLE
Kmeans with all duplicate cases crashes

### ISSUE THREAD

**Issue by carldister** [Cschimpf/Complex-It#5]
I was working on a work around for the prediction and created a iris.csv file where every single row was the same data.  By accident, I loaded it up first and tried to cluster.  It crashed.  Apparently the kmeans algorithm couldn't find a solution if all rows are equal.

**Comment by Cschimpf** [comment]
Yeah I would expect that to be the case. Kmeans tries to find the cluster arrangement that has the lowest sum of squares, but if all the rows are equal, then every solution would have the same sum of squares (for a given k) and the algorithm may not be able to resolve.
