### ISSUE TITLE
Can't Predict using Northeast Ohio Dataset

### ISSUE THREAD

**Issue by carldister** [Cschimpf/Complex-It#8]
Loaded the "Guesses" from the Northeast Ohio dataset.  Trained the SOM.  Then tried to predict using the "Training Set".  Locked up.

P.S. The Dataset folder for Northeast Ohio appears twice, in the root folder on Github and in the Data folder.  I think you should delete the one in the root and only leave it in the data folder

**Comment by Cschimpf** [comment]
You tried to use the predict tab or the simulation tab? Did it show an error? If you see an error in R it would be helpful to share that specific error with me.

**Comment by Cschimpf** [comment]
Also I don't think it was me who uploaded either of the Northeast Ohio databases? Are the two equivalent? if so I will just delete the one out of the root directory as you said.

**Comment by carldister** [comment]
I did - the two are redundant - I probably did it by accident with my git
issues.

I tried to use the predict tab here is the error, but I think it might have
something to do with having commas as separators between thousands - I used
the full training set and the full guesses set (four columns of data each):

Stack trace (innermost first):
    80: quality
    79: renderUI [C:\Users\carl\Desktop\Complex-It-master/server.R#178]
    78: func
    77: origRenderFunc
    76: output$trainnotice
     1: shiny::runApp
Warning: Error in predict.somRes: Number of columns of x.new does not
correspond to number of
             columns of the original data
Stack trace (innermost first):
    67: predict.somRes
    66: predict
    65: observeEventHandler
[C:\Users\carl\Desktop\Complex-It-master/server.R#299]
     1: shiny::runApp

CC

**Comment by Cschimpf** [comment]
Fixed, along with other predict tab issues.
